name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

concurrency:
  group: "CI: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:

  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: ubuntu-latest
          - os: windows-latest
      fail-fast: false
    uses: ./.github/workflows/run_gradle.yml
    with:
      runs-on: ${{ matrix.os }}
      ref: ${{ inputs.ref }}
      task: check
